In [ ]:
#this is just a comment ctrl+enter
print('hello')

hello

In [ ]:
import pandas as pd  #pandas is normally using in data analysis and manipulation library
path = '/content/drive/MyDrive/Dataset/housing.csv'
df = pd.read_csv(path)
df.head(5)  #show the first five row

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [ ]:

# A variable which stores an integer value
x = 13
print(f'hellooo {x}')
print(type(x))  #get datatype
#print(x)

#Operations
y = 12
z = x%y
print(f'z is :{z}')

hellooo 13
<class 'int'>
z is :1

In [ ]:
# A variable which stores a string
x = 'abcde'
print(type(x))
print(x) # write x also can in colab only

x = 'my name is yongzhun'
print(f'the char {x[2]}')  #indexing in python starts zero
print(f'The length of the string x is :{len(x)}') #prints the length of the string

y = ' and i am your teacher'

z = x + y
print(z)

<class 'str'>
abcde
the char
The length of the string x is :19
my name is yongzhun and i am your teacher

In [ ]:
#Conditionals
x = 5

if (x==3):
  print('Yay this is true!!!!')
else:
  print('Noooooo it is false')

if (x==3):
  print('yay')
elif (x==5):
  print('waaaaa')
else:
  print('heeeee')

Noooooo it is false
waaaaa

In [11]:
#For loops
'''

for i in range(10):
  print(i)

#list
x=[] #empty list
x=[1,2,3] # a list of numbers
x=[1, 'apples' ,10000]


print(f'-------')
x = ['apples','oranges','durian','bananas'] #x is a list of numbers ..it can also be x=['shah',1,3,'apples']
print(f'The list of x : {x}')
print(f'the length of list x: {(len(x))}')


print(f'-------')
for fruit in x:
  print(fruit)

x=['mangga','watermelon', 'musang-king','cempedak']
print(f'------')
for idx, fruit_name in enumerate(x):  #add index number to each item in x
  print(f'{idx} :{fruit_name}')

'''
x=['mangga','watermelon', 'musang-king','cempedak']
print(f'------')
for i in range(len(x)):
  print(i)

student_list = ['nabil', 'hani','ahmad','shahir','Aman','Adam']
print(f'length of student list : {len(student_list)}')
for w in range(len(student_list)):
  print(w)

count_a= 0
x = 'my name is yongzhun'
for char in x:
  if char == 'a':
    count_a +=1
print(f'The number of char a in string x is : {count_a}')

------
0
1
2
3
length of student list : 6
0
1
2
3
4
5
The number of char a in string x is : 1

In [22]:
#Functions (in java is called methods)
x = 1
y = 2

def addition(x,y):
  z = x + y
  return z

z = addition(x,y)
print(z)

3

In [23]:
#Multiplication table for 7 up to 17
for i in range(1, 18, 1):     #range(start,stop,step)
  print(f'{i}x7 = {i*7}')

1x7 = 7
2x7 = 14
3x7 = 21
4x7 = 28
5x7 = 35
6x7 = 42
7x7 = 49
8x7 = 56
9x7 = 63
10x7 = 70
11x7 = 77
12x7 = 84
13x7 = 91
14x7 = 98
15x7 = 105
16x7 = 112
17x7 = 119